import type { AnalysisResult, Finding } from "./analyze.js";
import type { CrawledPage } from "../lib/crawler.js";

function esc(s: string | null | undefined): string {
  if (s == null) return "";
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function tierClass(score: number): string {
  if (score >= 70) return "tier-good";
  if (score >= 50) return "tier-warn";
  return "tier-bad";
}

/**
 * Deliberately plain template-literal HTML, not React/JSX — this needs
 * to be a static file GitHub Pages can serve directly, generated by a
 * one-shot Node script in CI. No framework, no build step beyond
 * running this function and writing its output to disk.
 */
export function renderReportHtml(input: {
  startUrl: string;
  clientName: string;
  crawledAt: string;
  pages: CrawledPage[];
  analysis: AnalysisResult;
  personaLabel: string;
}): string {
  const { startUrl, clientName, crawledAt, pages, analysis, personaLabel } = input;
  const { scorecard, findings, templateAnalysis, componentAnalysis, featureMatrix, externalLinkHealth, keywords, phrases, integrations, plainTerms, uxLeadAssessment } = analysis;

  const actionPlan = [...findings].sort((a, b) => {
    const rank: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
    return (rank[a.severity] ?? 4) - (rank[b.severity] ?? 4);
  });

  const pageErrors = pages.filter((p) => p.error).length;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(clientName)} — ${esc(personaLabel)} Audit</title>
<style>
  :root {
    --paper: #f8fafc; --surface: #fff; --ink: #0f172a; --ink-dim: #64748b;
    --line: #e2e8f0; --good: #059669; --warn: #d97706; --bad: #dc2626;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--paper); color: var(--ink); font-family: -apple-system, "Segoe UI", Inter, sans-serif; font-size: 15px; line-height: 1.6; }
  .wrap { max-width: 1080px; margin: 0 auto; padding: 40px 24px 80px; }
  .kicker { font-family: ui-monospace, monospace; font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; color: var(--warn); margin-bottom: 8px; }
  h1 { font-size: 28px; margin: 0 0 6px; word-break: break-all; }
  .sub { color: var(--ink-dim); font-size: 14px; margin-bottom: 24px; }
  .grid { display: grid; gap: 12px; }
  .grid-4 { grid-template-columns: repeat(4, 1fr); }
  .grid-5 { grid-template-columns: repeat(5, 1fr); }
  .grid-2 { grid-template-columns: 1fr 1fr; }
  .card { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 16px; }
  .stat-num { font-size: 26px; font-weight: 600; }
  .stat-label { font-size: 11px; color: var(--ink-dim); text-transform: uppercase; margin-top: 4px; }
  .score-tile { text-align: center; padding: 20px 14px; }
  .score-tile .num { font-size: 34px; font-weight: 700; }
  .tier-good { color: var(--good); border-color: #a7f3d0; background: #ecfdf5; }
  .tier-warn { color: var(--warn); border-color: #fde68a; background: #fffbeb; }
  .tier-bad { color: var(--bad); border-color: #fecaca; background: #fef2f2; }
  section { margin: 32px 0; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.04em; color: var(--ink-dim); margin-bottom: 12px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--line); }
  th { font-size: 10.5px; text-transform: uppercase; color: var(--ink-dim); }
  .pill { display: inline-block; font-size: 10px; padding: 2px 8px; border-radius: 20px; font-family: ui-monospace, monospace; text-transform: uppercase; }
  .pill-high { background: #fef2f2; color: var(--bad); }
  .pill-medium { background: #fffbeb; color: var(--warn); }
  .pill-low { background: #ecfdf5; color: var(--good); }
  .url-cell { font-family: ui-monospace, monospace; font-size: 11.5px; color: var(--ink-dim); word-break: break-all; }
  .table-scroll { max-height: 420px; overflow-y: auto; border: 1px solid var(--line); border-radius: 8px; }
  ul.plain { padding-left: 20px; }
  @media (max-width: 800px) { .grid-4, .grid-5 { grid-template-columns: repeat(2, 1fr); } }
</style>
</head>
<body>
<div class="wrap">
  <div class="kicker">${esc(personaLabel)} Audit</div>
  <h1>${esc(startUrl)}</h1>
  <div class="sub">${esc(clientName)} — crawled ${pages.length} page(s), ${findings.length} finding(s) — ${esc(crawledAt)}</div>

  <section>
    <h2>Audit Coverage</h2>
    <div class="grid grid-4">
      <div class="card"><div class="stat-num">${pages.length}</div><div class="stat-label">Pages Crawled</div></div>
      <div class="card"><div class="stat-num">${pageErrors}</div><div class="stat-label">Page Errors</div></div>
      <div class="card"><div class="stat-num">${new Set(pages.map((p) => (p as any).templateFingerprint).filter(Boolean)).size || templateAnalysis.uniqueTemplateCount}</div><div class="stat-label">Unique Templates</div></div>
      <div class="card"><div class="stat-num">${componentAnalysis.uniqueComponentCount}</div><div class="stat-label">Unique Components</div></div>
    </div>
  </section>

  <section class="card">
    <h2>In Plain Terms</h2>
    <ul class="plain">${plainTerms.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>
  </section>

  <section class="card">
    <h2>${esc(personaLabel)}'s Assessment</h2>
    ${uxLeadAssessment.map((p) => `<p>${esc(p)}</p>`).join("")}
  </section>

  <section>
    <h2>Scorecard</h2>
    <div class="grid grid-5">
      <div class="card score-tile ${tierClass(scorecard.uxMaturityScore)}"><div class="num">${scorecard.uxMaturityScore}</div><div>Overall UX Maturity</div><div style="font-size:11px">${esc(scorecard.uxMaturityBand)}</div></div>
      <div class="card score-tile ${tierClass(scorecard.iaHealthScore)}"><div class="num">${scorecard.iaHealthScore}</div><div>Information Architecture</div></div>
      <div class="card score-tile ${tierClass(scorecard.contentQualityScore)}"><div class="num">${scorecard.contentQualityScore}</div><div>Content Quality</div></div>
      <div class="card score-tile ${tierClass(scorecard.accessibilityScore)}"><div class="num">${scorecard.accessibilityScore}</div><div>Accessibility</div></div>
      <div class="card score-tile ${tierClass(scorecard.seoScore)}"><div class="num">${scorecard.seoScore}</div><div>SEO &amp; Findability</div></div>
    </div>
  </section>

  <section class="grid grid-2">
    <div class="card">
      <h2>Tech Stack &amp; Integrations</h2>
      <ul class="plain">
        ${integrations.recognized.map((i) => `<li>${esc(i.name)} (${i.category}) — ${i.pagesFoundOn} page(s)</li>`).join("") || "<li>No recognized integrations detected.</li>"}
      </ul>
    </div>
    <div class="card">
      <h2>Feature Matrix</h2>
      <table>
        <thead><tr><th>Feature</th><th>Detected?</th><th>Pages</th></tr></thead>
        <tbody>${featureMatrix.map((f) => `<tr><td>${esc(f.feature)}</td><td>${f.detected ? "Yes" : "No"}</td><td>${f.detected ? f.pagesFoundOn : "—"}</td></tr>`).join("")}</tbody>
      </table>
    </div>
  </section>

  <section>
    <h2>Prioritized Action Plan</h2>
    <div class="card">
      ${
        actionPlan.length === 0
          ? "<p>No findings to prioritize — clean crawl.</p>"
          : actionPlan
              .map(
                (f: Finding) => `
        <div style="display:flex; gap:10px; padding:10px 0; border-bottom:1px solid var(--line);">
          <span class="pill pill-${f.severity === "critical" || f.severity === "high" ? "high" : f.severity === "medium" ? "medium" : "low"}">${esc(f.severity)}</span>
          <span style="flex:1">${esc(f.title)}.</span>
          <span style="font-size:11px; color:var(--ink-dim)">${f.affectedPageCount} page(s)</span>
        </div>`,
              )
              .join("")
      }
    </div>
  </section>

  <section>
    <h2>External Link Health</h2>
    <div class="card">
      <table>
        <thead><tr><th>Broken URL</th><th>Status</th><th>Linked From</th></tr></thead>
        <tbody>${
          externalLinkHealth.length === 0
            ? '<tr><td colspan="3">No broken external links found among the checked sample.</td></tr>'
            : externalLinkHealth.map((r) => `<tr><td class="url-cell">${esc(r.url)}</td><td>${esc(String(r.status))}</td><td>${r.linkedFromCount}</td></tr>`).join("")
        }</tbody>
      </table>
    </div>
  </section>

  <section>
    <h2>Keywords</h2>
    <div class="card table-scroll">
      <table>
        <thead><tr><th>Keyword</th><th>Occurrences</th><th>Pages</th><th></th><th>Top Phrases</th><th>Occurrences</th></tr></thead>
        <tbody>
        ${Array.from({ length: Math.max(keywords.length, phrases.length) }, (_, i) => {
          const k = keywords[i];
          const p = phrases[i];
          return `<tr><td>${esc(k?.keyword)}</td><td>${k?.occurrences ?? ""}</td><td>${k?.pagesFoundOn ?? ""}</td><td></td><td>${esc(p?.phrase)}</td><td>${p?.occurrences ?? ""}</td></tr>`;
        }).join("")}
        </tbody>
      </table>
    </div>
  </section>

  <section>
    <h2>Templates</h2>
    <div class="card table-scroll">
      <table>
        <thead><tr><th>Fingerprint</th><th>Page Count</th><th>Example URL</th></tr></thead>
        <tbody>${templateAnalysis.templates.map((t) => `<tr><td class="url-cell">${esc(t.fingerprint)}</td><td>${t.pageCount}</td><td class="url-cell">${esc(t.exampleUrl)}</td></tr>`).join("")}</tbody>
      </table>
    </div>
  </section>

  <section>
    <h2>Full Page Inventory</h2>
    <div class="card table-scroll">
      <table>
        <thead><tr><th>URL</th><th>Status</th><th>Title</th><th>Words</th><th>Depth</th><th>Error</th></tr></thead>
        <tbody>
        ${pages
          .map(
            (p) => `<tr>
          <td class="url-cell">${esc(p.url)}</td>
          <td>${p.statusCode ?? "—"}</td>
          <td>${esc(p.title)}</td>
          <td>${p.wordCount}</td>
          <td>${p.depth}</td>
          <td>${esc(p.error)}</td>
        </tr>`,
          )
          .join("")}
        </tbody>
      </table>
    </div>
  </section>

</div>
</body>
</html>`;
}
